---
- name: Install Istio.
  hosts: Pisc0
  connection: local
  gather_facts: yes
  vars:
    istio_ms_hostname_and_profile: openshift0

  roles:
    - role: ansible-role-istio
      istio:
        action_to_trigger: clean  # [ deploy | clean ]
        action:
          deploy:
            istioctl: true    # istioctl
            core: true        # core components
            addons: true      # prometheus, graphana, zipkin, servicegraph
            sample_apps: true # bookinfo
          clean: true
        minishift:
          profile: "{{ istio_ms_hostname_and_profile }}"
        openshift:
          project: istio-system    # default
          hostname: "{{ istio_ms_hostname_and_profile }}"
          admin_usr: "system:admin"
          admin_pwd: anypassword
          istio_usr: developer
          istio_pwd: anypassword
        repo:
          #release_tag_name: "0.2.12"
          #release_tag_name: "0.2.10"
          #release_tag_name: "0.2.9"
          release_tag_name: "0.2.7"
          #release_tag_name: "0.2.6"
          #release_tag_name: "0.2.4"
          #release_tag_name: "0.2.2"
          #release_tag_name: "0.2.1"
          #release_tag_name: "0.2.0"
          #release_tag_name: "0.1.6"
          #release_tag_name: "0.1.5"
