- name: clean | Delete 'istioctl' to the 'bin' directory
  file:
    path: "{{ __i.dir.local_bin }}/istioctl"
    state: absent
  become: yes

- name: clean | Removing BookInfo App
  command: "{{ item }}"
  with_items:
    - "{{ my_oc }} delete project bookinfo"
  ignore_errors: yes

- name: clean | Removing Weave-Scope
  command: "{{ item }}"
  with_items:
    - "{{ my_oc }} delete --namespace weave-scope -f https://cloud.weave.works/k8s/scope.yaml"
    - "{{ my_oc }} delete project weave-scope"
  ignore_errors: yes

- name: clean | Removing Istio addons
  command: "{{ item }}"
  with_items:
    - "{{ my_oc }} delete -f istio-{{ __i.repo.release_tag_name }}/install/kubernetes/addons/zipkin.yaml"         ## zipkin for tracing
    - "{{ my_oc }} delete -f istio-{{ __i.repo.release_tag_name }}/install/kubernetes/addons/prometheus.yaml"     ## prometheus for metrics
    - "{{ my_oc }} delete -f istio-{{ __i.repo.release_tag_name }}/install/kubernetes/addons/grafana.yaml"        ## grafana for visualizing metrics generated for prometheus
    - "{{ my_oc }} delete -f istio-{{ __i.repo.release_tag_name }}/install/kubernetes/addons/servicegraph.yaml"   ## visualize microservices call map
  args:
    chdir: "{{ __i.dir.local_repo }}/{{ istio_asset_name_without_ext }}"
  ignore_errors: yes  ### to ignore error when trying remove resources that doesnt exist.

- name: clean | Removing Istio core
  command: "{{ my_oc }} delete -f istio-{{ __i.repo.release_tag_name }}/install/kubernetes/istio-auth.yaml"
  args:
    chdir: "{{ __i.dir.local_repo }}/{{ istio_asset_name_without_ext }}"
  ignore_errors: yes ### to ignore error when trying remove resources that doesnt exist.

- name: clean | Removing Istio entries from '/etc/hosts'
  lineinfile:
    dest: /etc/hosts
    line: '{{ item }}'
    state: absent
  with_items:
    - "{{ instance_ip_address.stdout }}  zipkin-istio-system.{{ instance_ip_address.stdout }}.nip.io"
    - "{{ instance_ip_address.stdout }}  grafana-istio-system.{{ instance_ip_address.stdout }}.nip.io"
    - "{{ instance_ip_address.stdout }}  servicegraph-istio-system.{{ instance_ip_address.stdout }}.nip.io"
    - "{{ instance_ip_address.stdout }}  istio-ingress-istio-system.{{ instance_ip_address.stdout }}.nip.io"
  become: yes
