- name: set_oc | Check if 'oc' binary exists in PATH
  stat:
    path: "{{ __i.dir.local_bin }}/oc"
  register: oc_current_client

- name: set_oc | Get the path to the 'oc' client for Minishift '{{ __i.minishift.profile }}' instance
  find:
    #paths: "{{ lookup('env', 'HOME') }}/.minishift/profiles/{{ __i.start_options.profile }}/cache/oc"   ## openshift < v3.7
    paths: "{{ lookup('env', 'HOME') }}/.minishift/cache/oc/"   ## openshift v3.7
    patterns: "{{ ansible_os_family | lower }}"
    recurse: yes
    hidden: yes
    file_type: directory
  register: oc_versions

- name: set_oc | Initializing 'my_oc' fact
  set_fact:
    my_oc: "{{ __i.dir.local_bin }}/oc"

- name: set_oc | Set 'my_oc' with last value of 'oc_versions.files'
  set_fact:
    my_oc: "{{ (oc_versions.files | last).path }}/oc"
  when: oc_versions.files | length == 1 and not oc_current_client.stat.exists
